[package]
name = "portforwarder-rs"
version = "0.1.0"
authors = ["Paweł Zmarzły <pawo2500@gmail.com>"]

[dependencies]
get_if_addrs = "0.4.0"
igd = "0.6.0"
chan = "0.1.21"
chan-signal = "0.3.1"

[profile.release]
lto = true
